services:
  tif-ide:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      - .:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - ./src/rooms:/app/src/rooms
    init: true
