services:
  tif-ide-rework:
    container_name: tif-ide
    build: .
    ports:
      - "3000:3000"
    environment:
      - RUNNING_IN_DOCKER=true
      - PROJECT_DIR=${PWD}
    volumes:
      - ${ROOMS_PATH}:/app/rooms
      - /var/run/docker.sock:/var/run/docker.sock
    init: true
